default:
  image: debian-bullseye-go-builder:v1

# Is performed before the scripts in the stages step
before_script:
  - source /etc/profile
  # Load the ssh private key from the gitlab build variables to enable dupload
  # to connect to the repo via scp
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan repo.stusta.mhn.de >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

# Defines stages which are to be executed
stages:
  - build_bullseye
  - upload_to_repo

build_bullseye:
  stage: build_bullseye
  script:
    - apt-get install -y golang-go
    - mkdir $PWD/.go/
    - export GOPATH=$PWD/obj-x86_64-linux-gnu/
    - go get
    - echo $GOPATH
    - ls $GOPATH
    - dpkg-buildpackage -us -uc
    - mkdir -p build/
    - mv ../wumpe*.deb build/
    - mv ../wumpe*.changes build/
    - mv ../wumpe*.tar.gz build/
    - mv ../wumpe*.dsc build/
    - mv ../wumpe*.buildinfo build/

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

upload_to_repo:
  stage: upload_to_repo
  script:
    - echo "Uploading debian package to ssn repository"
    - ssh repo@repo.stusta.mhn.de "echo SSH-Connection working"
    - dupload -f -t ssn_repo build/wumpe*.changes
  when: manual
  only: 
    - master
